
[build]
  command = "npm run build"
  publish = "dist"

# Règle de redirection pour les applications SPA avec sous-chemin /diagnostic/
[[redirects]]
  from = "/diagnostic/*"
  to = "/diagnostic/index.html"
  status = 200
